budlabs/i3ass

- i3fyra/i3fyra
> resolved issues when toggling windows in i3fyra

- i3fyra/README.md
- i3fyra/i3fyra
- i3fyra/i3fyra.1
- i3viswiz/i3viswiz
There was a bug in i3viswiz, which disabled the focus functionality. It is fixed now.
Also fixed a bug in i3fyra that was related to negative split sizes.  
Added `-t` option to i3fyra, to set a different target window then the active one.
> viswiz bug fixed 

- i3fyra/i3fyra
- i3viswiz/i3viswiz
changed i3fyra -m behaviour a bit, to be more stable. And added workspace position to i3viswiz, to account for multimontior setups.
> fixed issues with moving and focussing on multimonitor setups

- README.md
- i3Kornhe/i3Kornhe
- i3fyra/i3fyra
- i3viswiz/i3viswiz
this should make issue #20 much less likely to happen.
> bug fixes in i3viswiz and i3fyra

- i3fyra/i3fyra
> i3fyra: apllysplits default current split value bug fixed

- README.md
- i3Kornhe/i3Kornhe
- i3Kornhe/i3Kornhe.1
- i3get/i3get
fixed various issues in i3Kornhe
> Nicer Kornhe

- README.md
- man/i3ass.1
- man/i3fyra.1
- man/i3menu.1
- man/i3run.1
- src/i3ass
- src/i3fyra
- src/i3menu
- src/i3run
Added long awaited `--force` option to i3run
> 2020.01.26.6 - release

- src/i3get
- src/i3run
Synk didn't start till a window event happened. refactored the sync loop.
> [FIX] i3get : fixed issue whith --synk

- src/i3run
also removed deprecation warning from --command.
cleaned up code to make shellcheck happy.
updated manpage and docs to reflect changes.
fixes: #101 #103
> [ADD] properly handling multiple criteria and new rename options

- src/i3fyra
- src/i3king
> Single win king

- src/i3king
this can be done externally using --conid and --print-commands options.
which is how we do it in i3fyra.
This also adds ON_CLOSE directive . #108  #106
> [REMOVE] --float-toggle option

- src/i3viswiz
Fixes issue #118 (toggle focus between floating windows)
> [FIX] Corrected typo that prevented focus shifting on floating windows.

- src/i3king
Also changed path to pid file (XDG_RUNTIME_DIR/i3ass/i3king.pid)
Fixes: #137
> [ADD] trap for USR1

- share/Makefile
> got_func fix

- README.md
- docs/readme_about.md
- docs/releasenotes/0next.md
- docs/releasenotes/2022.05.20.md
- share/Makefile
- src/i3Kornhe/config.mak
- src/i3flip/config.mak
- src/i3fyra/config.mak
- src/i3get/config.mak
- src/i3gw/config.mak
- src/i3king/config.mak
- src/i3list/config.mak
- src/i3menu/config.mak
- src/i3run/config.mak
- src/i3var/config.mak
- src/i3viswiz/config.mak
- src/i3zen/config.mak
> [FIX] build process typo `@$ -> $@`

- Makefile
- src/i3run/config.mak
- src/i3run/func/focuswindow.sh
- src/i3run/i3run
> 2022-05-22 release

- share/Makefile
- share/share.mak
i have gotten report on installation sometimes failing due to makefile problems.
hopefully this PR resolve this. I am not 100% sure, since the issue in question
is hard to replicate..
> makefile improvements

- src/i3viswiz/config.mak
- src/i3viswiz/i3viswiz
> [FIX] viswiz, stricter about direction argument

- src/i3fyra/config.mak
- src/i3fyra/i3fyra
> [FIX] fyra, stricter argument parsing

- src/i3Kornhe/config.mak
- src/i3Kornhe/i3Kornhe
> [FIX] Kornhe be stricter and more verbose on arguments

- src/i3zen/config.mak
- src/i3zen/func/create_zen_workspace.sh
- src/i3zen/func/move_to_zen_container.sh
- src/i3zen/func/next_vacant_workspace.sh
- src/i3zen/func/tile_with_i3king.sh
- src/i3zen/func/unzen_container.sh
- src/i3zen/i3zen
refactored the code for maintainability/readability, fixed a minor issue (#202 ). and by moving code around it should be slightly faster now (f.i. it only finds the next vacant workspace if it needs to).
> [i3zen] maintainability

- src/i3flip/config.mak
- src/i3flip/docs/description.md
- src/i3flip/i3flip
- src/i3flip/i3flip.1
use similar parsing as with i3viswiz and i3Khorne
> [i3flip] strict argument parsing
